[package]
name = "cargo-localize"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.18"
toml_edit = "0.22"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.5"
fs_extra = "1.3"
dirs = "5.0"
pathdiff = "0.2"
